name: dumbpkg
description: A dumb package for testing various CI integrations.
version: 1.0.2
repository: https://github.com/bartekpacia/dumbpkg

environment:
  sdk: '>=2.19.3 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
