name: Run Android emulator

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-24.04

    env:
      ANDROID_HOME: /home/runner/androidsdk
      ANDROID_SDK_ROOT: /home/runner/androidsdk

    steps:
      - name: Enable KVM group perms
        run: |
            echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
            sudo udevadm control --reload-rules
            sudo udevadm trigger --name-match=kvm

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 8

      - name: Set up bartekpacia/scripts
        run: |
          git clone https://github.com/bartekpacia/scripts.git
          echo "$PWD/scripts/bin" >> $GITHUB_PATH

      - name: Set up Android Command-line Tools
        run: |
          # v8, latest working on Java 8
          bash $(which install_android_sdk) https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip
          echo "$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $GITHUB_PATH

          curl -fsSl -O https://raw.githubusercontent.com/travis-ci/travis-cookbooks/master/community-cookbooks/android-sdk/files/default/android-wait-for-emulator
          chmod +x ./android-wait-for-emulator
          echo "$PWD" >> $GITHUB_PATH
          
      - name: Set up Android SDK components
        run: |
          yes | sdkmanager --install emulator
          echo "$ANDROID_HOME/emulator" >> $GITHUB_PATH
          yes | sdkmanager --install "platform-tools"
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          yes | sdkmanager --install "platforms;android-34"
          yes | sdkmanager --install "system-images;android-34;google_apis;x86_64"

      - name: Create AVD
        run: |
          avdmanager -s create avd \
            --package "system-images;android-34;google_apis;x86_64" \
            --name "MyAVD"

          cat << EOF >> ~/.android/avd/MyAVD.avd/config.ini
          hw.cpu.ncore=2
          hw.gpu.enabled=yes
          hw.gpu.mode=swiftshader_indirect
          hw.ramSize=3072
          disk.dataPartition.size=4G
          vm.heapSize=576
          hw.lcd.density=440
          hw.lcd.height=2220
          hw.lcd.width=1080
          EOF
      
      - name: Run AVD
        run: |
          emulator @MyAVD \
            -verbose -no-snapshot-save -no-window -noaudio -no-boot-anim -accel on \
            >~/emulator_stdout.log \
            2>~/emulator_stderr.log &

      - name: Wait for emulator to start
        run: android-wait-for-emulator

      